# Generated by Django 5.2.9 on 2025-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_options_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], db_index=True, default='Not Started', max_length=20),
        ),
    ]
